name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate light stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=vue&show_icons=true&include_all_commits=true&hide_rank=true
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate dark stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=transparent&show_icons=true&include_all_commits=true&hide_rank=true
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime dark card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&layout=compact&theme=transparent&hide_title=true
          path: profile/wakatime-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime light card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&layout=compact&theme=vue&hide_title=true
          path: profile/wakatime-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
